export const content = {
  stats: {
    applescotti: [
      "<div class='content-item'>Official Name = Bella Toka 12/22/24 Gelato 33 Zone 1</div>",
      "<div class='content-item'>Clones received = 03/16/2024</div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'>Plants cut down and hung = 12/22/2024</div>",
      "<div class='content-item'>Plants first trim = 01/28/2025</div>",
      "<div class='content-item'>Plants cured = 02/19/2025</div>",
      "<div class='content-item'>Plants second trim = 05/06/2025</div>",
    ].join(""),
    "gelato-33": [
      "<div class='content-item'>Clones received =03/16/2024</div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'>Plants cut down and hung = 12/22/2024</div>",
      "<div class='content-item'>Plants first trim = 03/25/2025</div>",
      "<div class='content-item'>Plants cured = 04/08/2025</div>",
      "<div class='content-item'>Plants second trim = 05/06/2025</div>",
    ].join(""),
    "blue-dream": [
      "<div class='stats-section'>",
      "<h4 style='color: #4a90e2; margin-bottom: 10px; border-bottom: 2px solid #4a90e2; padding-bottom: 5px;'>📅 Timeline</h4>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e8f4fd, #d1e9f6); border-left: 4px solid #4a90e2; padding: 10px; margin: 5px 0;'>",
      "<strong>🌱 Clones Received:</strong> August 1, 2025",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #fff3cd, #ffeaa7); border-left: 4px solid #f39c12; padding: 10px; margin: 5px 0;'>",
      "<strong>🔍 Quality Control (B):</strong> August 1, 2025 ✅",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #f8d7da, #f5c6cb); border-left: 4px solid #e74c3c; padding: 10px; margin: 5px 0;'>",
      "<strong>⚠️ QC Issues:</strong> Thrips, Algae (5+), Leaf Burn - August 1, 2025",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #d4edda, #c3e6cb); border-left: 4px solid #28a745; padding: 10px; margin: 5px 0;'>",
      "<strong>🛡️ Regalia CG Treatment:</strong> August 2, 2025 ✅",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>🌿 Transplant (A):</strong> August 2, 2025 ✅",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #fff3cd, #ffeaa7); border-left: 4px solid #ffc107; padding: 10px; margin: 5px 0;'>",
      "<strong>⏳ Status:</strong> Pending - August 2025",
      "</div>",
      "</div>",
      "<div class='stats-section' style='margin-top: 20px;'>",
      "<h4 style='color: #4a90e2; margin-bottom: 10px; border-bottom: 2px solid #4a90e2; padding-bottom: 5px;'>📊 Data</h4>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>🧪 Lab Reports:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>⚖️ Yield Data:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>🌱 Carbon Footprint:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>👥 Labor Stats:</strong> Pending",
      "</div>",
      "</div>"
    ].join(""),
    "p81": [
      "<div class='stats-section'>",
      "<h4 style='color: #4a90e2; margin-bottom: 10px; border-bottom: 2px solid #4a90e2; padding-bottom: 5px;'>📅 Timeline</h4>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e8f4fd, #d647b2ff); border-left: 4px solid #cf41a0ff; padding: 10px; margin: 5px 0;'>",
      "<strong>🌱 Number of Weeks:</strong> 0",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e8f4fd, #d1e9f6); border-left: 4px solid #4a90e2; padding: 10px; margin: 5px 0;'>",
      "<strong>🌱 First Clones Received:</strong> August 8, 2025",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #fff3cd, #ffeaa7); border-left: 4px solid #f39c12; padding: 10px; margin: 5px 0;'>",
      "<strong>🔍 First Quality Control (B):</strong> August 8, 2025",
      "</div>",
      "</div>",
      "<div class='stats-section' style='margin-top: 20px;'>",
      "<h4 style='color: #4a90e2; margin-bottom: 10px; border-bottom: 2px solid #4a90e2; padding-bottom: 5px;'>📊 Data</h4>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>🧪 Lab Reports:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>⚖️ Yield Data:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>🌱 Carbon Footprint:</strong> Pending",
      "</div>",
      "<div class='content-item' style='background: linear-gradient(135deg, #e2e3e5, #d6d8db); border-left: 4px solid #6c757d; padding: 10px; margin: 5px 0;'>",
      "<strong>👥 Labor Stats:</strong> Pending",
      "</div>",
      "</div>"
    ].join("")
  },
  nutrients: {
    applescotti: [
      "<div style='display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px;'>",
      "<div class='nutrient-stage-container'>",
      "<h3>Vegetative Stage</h3>",
      "<div class='nutrient-stage-content' ref='vegetativeRef'>",
      "<div class='nutrient-loop-container' style='transform: translateY(-{vegetativeScroll}px)'>",
      "<div class='content-item clickable' data-image='power-si' style='font-weight: 600;'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='roots-gold'>House and Garden Roots Excelurator Gold</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='liquid-karma'>Botanicare Liquid Karma</div>",
      "<div class='content-item clickable' data-image='vitamino'>Botanicare Vitamino</div>",
      "<div class='content-item clickable' data-image='nitrogen-boost'>House and Garden Nitrogen Boost</div>",
      "<div class='content-item clickable' data-image='power-si' style='font-weight: 600;'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='roots-gold'>House and Garden Roots Excelurator Gold</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='liquid-karma'>Botanicare Liquid Karma</div>",
      "<div class='content-item clickable' data-image='vitamino'>Botanicare Vitamino</div>",
      "<div class='content-item clickable' data-image='nitrogen-boost'>House and Garden Nitrogen Boost</div>",
      "</div>",
      "</div>",
      "</div>",
      "<div class='nutrient-stage-container'>",
      "<h3>Flower Stage</h3>",
      "<div class='nutrient-stage-content' ref='floweringRef'>",
      "<div class='nutrient-loop-container' style='transform: translateY(-{floweringScroll}px)'>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='paleo-bloom'>Primordial Solutions PaleoBloom</div>",
      "<div class='content-item clickable' data-image='true-blooms'>Primordial Solutions True Blooms</div>",
      "<div class='content-item clickable' data-image='hydroplex'>Botanicare Hydroplex</div>",
      "<div class='content-item clickable' data-image='bud-xl'>House and Garden Bud-XL</div>",
      "<div class='content-item clickable' data-image='sweet-raw'>Botanicare Sweet Raw</div>",
      "<div class='content-item clickable' data-image='sweet'>Botanicare Sweet Berry</div>",
      "<div class='content-item clickable' data-image='top-shooter'>House and Garden Top Shooter</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='paleo-bloom'>Primordial Solutions PaleoBloom</div>",
      "<div class='content-item clickable' data-image='true-blooms'>Primordial Solutions True Blooms</div>",
      "<div class='content-item clickable' data-image='hydroplex'>Botanicare Hydroplex</div>",
      "<div class='content-item clickable' data-image='bud-xl'>House and Garden Bud-XL</div>",
      "<div class='content-item clickable' data-image='sweet-raw'>Botanicare Sweet Raw</div>",
      "<div class='content-item clickable' data-image='sweet'>Botanicare Sweet Berry</div>",
      "<div class='content-item clickable' data-image='top-shooter'>House and Garden Top Shooter</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "</div>",
      "</div>",
      "</div>",
      "<div class='nutrient-stage-container'>",
      "<h3>Images</h3>",
      "<div class='nutrient-stage-content' ref='imagesRef'>",
      "<div class='nutrient-loop-container' style='transform: translateY(-{imagesScroll}px)'>",
      "<div class='content-item clickable' data-image='Img_1'>Img_1</div>",
      "<div class='content-item clickable' data-image='Img_2'>Img_2</div>",
      "<div class='content-item clickable' data-image='Img_3'>Img_3</div>",
      "<div class='content-item clickable' data-image='Img_4'>Img_4</div>",
      "<div class='content-item clickable' data-image='Img_5'>Img_5</div>",
      "<div class='content-item clickable' data-image='Img_6'>Img_6</div>",
      "<div class='content-item clickable' data-image='Img_7'>Img_7</div>",
      "<div class='content-item clickable' data-image='Img_8'>Img_8</div>",
      "<div class='content-item clickable' data-image='Img_1'>Img_1</div>",
      "<div class='content-item clickable' data-image='Img_2'>Img_2</div>",
      "<div class='content-item clickable' data-image='Img_3'>Img_3</div>",
      "<div class='content-item clickable' data-image='Img_4'>Img_4</div>",
      "<div class='content-item clickable' data-image='Img_5'>Img_5</div>",
      "<div class='content-item clickable' data-image='Img_6'>Img_6</div>",
      "<div class='content-item clickable' data-image='Img_7'>Img_7</div>",
      "<div class='content-item clickable' data-image='Img_8'>Img_8</div>",
      "</div>",
      "</div>",
      "</div>",
      "</div>",
    ].join(""),
    "gelato-33": [
      "<div style='display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px;'>",
      "<div class='nutrient-stage-container'>",
      "<h3>Vegetative Stage</h3>",
      "<div class='nutrient-stage-content'>",
      "<div class='content-item clickable' data-image='power-si' style='font-weight: 600;'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a' style='font-weight: 600;'>House and Garden Coco A</div>",
      "<div class='content-item clickable' data-image='cocos-b' style='font-weight: 600;'>House and Garden Coco B</div>",
      "<div class='content-item clickable' data-image='cal-mag' style='font-weight: 600;'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar' style='font-weight: 600;'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='roots-gold' style='font-weight: 600;'>House and Garden Roots Excelurator Gold</div>",
      "<div class='content-item clickable' data-image='hydroguard' style='font-weight: 600;'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='sea-green' style='font-weight: 600;'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='liquid-karma' style='font-weight: 600;'>Botanicare Liquid Karma</div>",
      "<div class='content-item clickable' data-image='vitamino' style='font-weight: 600;'>Botanicare Vitamino</div>",
      "<div class='content-item clickable' data-image='nitrogen-boost' style='font-weight: 600;'>House and Garden Nitrogen Boost</div>",
      "</div>",
      "</div>",
      "<div class='nutrient-stage-container'>",
      "<h3>Flower Stage</h3>",
      "<div class='nutrient-stage-content'>",
      "<div class='content-item clickable' data-image='power-si' style='font-weight: 600;'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a' style='font-weight: 600;'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b' style='font-weight: 600;'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag' style='font-weight: 600;'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar' style='font-weight: 600;'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='hydroguard' style='font-weight: 600;'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='paleo-bloom' style='font-weight: 600;'>Primordial Solutions PaleoBloom</div>",
      "<div class='content-item clickable' data-image='true-blooms' style='font-weight: 600;'>Primordial Solutions True Blooms</div>",
      "<div class='content-item clickable' data-image='hydroplex' style='font-weight: 600;'>Botanicare Hydroplex</div>",
      "<div class='content-item clickable' data-image='bud-xl' style='font-weight: 600;'>House and Garden Bud-XL</div>",
      "<div class='content-item clickable' data-image='sweet-raw' style='font-weight: 600;'>Botanicare Sweet Raw</div>",
      "<div class='content-item clickable' data-image='sweet' style='font-weight: 600;'>Botanicare Sweet Berry</div>",
      "<div class='content-item clickable' data-image='top-shooter' style='font-weight: 600;'>House and Garden Top Shooter</div>",
      "<div class='content-item clickable' data-image='sea-green' style='font-weight: 600;'>Primordial Solutions Sea Green</div>",
      "</div>",
      "</div>",
      "<div class='nutrient-stage-container'>",
      "<h3>Schedule Images</h3>",
      "<div class='nutrient-stage-content'>",
      "<div class='content-item clickable' data-image='Img_1' style='font-weight: 600;'>Img_1</div>",
      "<div class='content-item clickable' data-image='Img_2' style='font-weight: 600;'>Img_2</div>",
      "<div class='content-item clickable' data-image='Img_3' style='font-weight: 600;'>Img_3</div>",
      "<div class='content-item clickable' data-image='Img_4' style='font-weight: 600;'>Img_4</div>",
      "<div class='content-item clickable' data-image='Img_5' style='font-weight: 600;'>Img_5</div>",
      "<div class='content-item clickable' data-image='Img_6' style='font-weight: 600;'>Img_6</div>",
      "<div class='content-item clickable' data-image='Img_7' style='font-weight: 600;'>Img_7</div>",
      "<div class='content-item clickable' data-image='Img_8' style='font-weight: 600;'>Img_8</div>",
      // "<div class='content-item clickable' data-image='full-schedule' style='font-weight: 600;'>Full Schedule</div>",
      "</div>",
      "</div>",
      "</div>"
    ].join(""),
    "blue-dream": [
      "<div></div>"
    ].join(""),
    "p81": [
      "<div></div>"
    ].join(""),
  },
  "pest-management": {
    applescotti: [
      "<div class='content-item clickable' data-image='neem-oil' style='font-weight: 600;'>Neem Oil <a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='regalia' style='font-weight: 600;'>Regalia CG Biofungicide <a href='#' onclick='window.open(\"https://profarmgroup.com/products/regalia-cg\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='molt-x' style='font-weight: 600;'>Molt-X <a href='#' onclick='window.open(\"https://bioworksinc.com/products/moltx/\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='dr-zymes' style='font-weight: 600;'>The Amazing Doctor Zymes <a href='#' onclick='window.open(\"https://www.doctorzymes.com/pesticide-free-insecticide.php\", \"_blank\")'>Link</a></div>",

      "<div class='content-item'><a href='/pesticide-list'>Full List of Legal Pesticides for Indoor Cannabis Cultivation</a></div>",
    ].join(""),
    "gelato-33": [
      "<div class='content-item clickable' data-image='neem-oil' style='font-weight: 600;'>Neem Oil <a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='regalia' style='font-weight: 600;'>Regalia CG Biofungicide <a href='#' onclick='window.open(\"https://profarmgroup.com/products/regalia-cg\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='molt-x' style='font-weight: 600;'>Molt-X <a href='#' onclick='window.open(\"https://bioworksinc.com/products/moltx/\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='dr-zymes' style='font-weight: 600;'>The Amazing Doctor Zymes <a href='#' onclick='window.open(\"https://www.doctorzymes.com/pesticide-free-insecticide.php\", \"_blank\")'>Link</a></div>",

      "<div class='content-item'><a href='/pesticide-list'>Full List of Legal Pesticides for Indoor Cannabis Cultivation</a></div>",
    ].join(""),
    "blue-dream": [
      "<div class='content-item clickable' data-image='neem-oil' style='font-weight: 600;'>Neem Oil <a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='regalia' style='font-weight: 600;'>Regalia CG Biofungicide <a href='#' onclick='window.open(\"https://profarmgroup.com/products/regalia-cg\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='dr-zymes' style='font-weight: 600;'>The Amazing Doctor Zymes <a href='#' onclick='window.open(\"https://www.doctorzymes.com/pesticide-free-insecticide.php\", \"_blank\")'>Link</a></div>",

      "<div class='content-item'><a href='/pesticide-list'>Full List of Legal Pesticides for Indoor Cannabis Cultivation</a></div>",
    ].join(""),
    "p81": [
      "<div class='content-item clickable' data-image='neem-oil' style='font-weight: 600;'>Neem Oil <a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='regalia' style='font-weight: 600;'>Regalia CG Biofungicide <a href='#' onclick='window.open(\"https://profarmgroup.com/products/regalia-cg\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='dr-zymes' style='font-weight: 600;'>The Amazing Doctor Zymes <a href='#' onclick='window.open(\"https://www.doctorzymes.com/pesticide-free-insecticide.php\", \"_blank\")'>Link</a></div>",

      "<div class='content-item'><a href='/pesticide-list'>Full List of Legal Pesticides for Indoor Cannabis Cultivation</a></div>",
    ].join(""),
  },
};